name: Run Python Script with Selenium on Windows  
  
on:  
  #手动触发方便测试
  repository_dispatch:  
    types: [manual-trigger]
  
jobs:  
  run_python_script:  
    runs-on: windows-latest  
  
    steps:  
      - uses: actions/checkout@v2  
  
      - name: Set up Python  
        uses: actions/setup-python@v2  
        with:  
          python-version: '3.x'  # 或者你需要的 Python 版本  
  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install selenium  
		  pip install feedparser # 假设你的脚本需要 requests  库rss获取地址
          pip install pytube # 下载视频
          pip install moviepy # 音频转视频
          pip install python-dateutil #处理日期插件
          pip install pytz
          pip install beautifulsoup4
          pip install selenium  
          pip install lxml
  
      - name: Download and setup ChromeDriver  
        run: |  
          # 注意：此URL可能需要更新为ChromeDriver的最新版本  
          $url = "https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.201/win64/chromedriver-win64.zip"  
          Invoke-WebRequest -Uri $url -OutFile chromedriver.zip  
          Expand-Archive chromedriver.zip -DestinationPath .  
          Move-Item .\chromedriver-win64\chromedriver.exe C:\ProgramData\hsscWork\bin\  # 或者其他系统PATH中的目录  
	  - name: 下载仓库代码
	    run: |
	      git clone https://xiongod:${{ secrets.ACCESS_TOKEN }}@github.com/xiongod/hsscWork.git  
	      cd hsscWork  
	      git config user.name "xiongod"  
	      git config user.email "xiongod@outlook.com"
		  
      - name: Run Python script  
        run: |
          dir
          python mian.py  # 确保文件名正确  
		  
	  - name: 把处理好的文件复制到git仓库中
        working-directory: ./
        run: |
          cp -r ./* ./hsscWork/
      # 提交并推送更改
      - name: 提交仓库
        working-directory: ./hsscWork
        run: |
          git add .
          git commit -m "Adding mp3 via GitHub Actions"  
          git push origin HEAD:main
        env:
          # 在仓库设置中创建一个名为 IMAGES_REPO_PAT 的 secret，并存储您的 Personal Access Token
          IMAGES_REPO_PAT: ${{ secrets.ACCESS_TOKEN }}
  
      # （可选）清理步骤，删除下载的ChromeDriver zip文件  
      - name: Cleanup  
        run: |  
          Remove-Item chromedriver.zip
